import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Providers } from "@/lib/client/components/Providers";
import { getLocale, getMessages } from "next-intl/server";
import { LanguageSelector } from "@/lib/client/components/LanguageSelector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const translations = await getMessages();

  return (
    <Providers translations={translations} locale={locale}>
      <html lang={locale} className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}

          <LanguageSelector />
        </body>
      </html>
    </Providers>
  );
}

// TODO: should there be a lng param: Yes, probably. Link: https://webmasters.stackexchange.com/questions/403/how-should-i-structure-my-urls-for-both-seo-and-localization/44289?newreg=ec84001177994fcf8db060f884cc7cf3
// TODO: emails with react-mail
// TODO: site metadata
// TODO: basic demo of some ICU formats and rich text rendering
//
// DONE: get language from user's preferences or fallback to auto-detect
// DONE: zod
// DONE: place translation resources into json files
// DONE: typesafetify
// DONE: create language selector
